### ISSUE TITLE
inspectplan can't pull docker image

### ISSUE THREAD

**Issue by bbotte** [kubesphere/kubeeye#354]
```
[root@k8s-master-001 kubeeye-offline-v1.0.6]# kubectl get jobs  -n kubeeye-system
NAME                                         STATUS    COMPLETIONS   DURATION   AGE
inspectplan-20250430-18-00-component-flsl2   Running   0/1           91s        91s
inspectplan-20250430-18-00-opa-r97ng         Running   0/1           91s        91s
[root@k8s-master-001 kubeeye-offline-v1.0.6]# kubectl get po  -n kubeeye-system
NAME                                               READY   STATUS             RESTARTS   AGE
inspectplan-20250430-18-00-component-flsl2-c47g2   0/1     ImagePullBackOff   0          92s
inspectplan-20250430-18-00-opa-r97ng-tfz49         0/1     ImagePullBackOff   0          92s
kubeeye-controller-manager-6569465847-45pls        3/3     Running            0          2m9s
```

Error: ImagePullBackOff

```
kubectl edit cm kubeeye-config -n kubeeye-system
apiVersion: v1
data:
  config: |-
    job:
      autoDelTime: 30
      backLimit: 5
      image: harbor.test.com/devops/kubeeye-job:v1.0.6
      imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: harbor-test
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
      multiCluster:
        member1:
          image: harbor.test.com/devops/kubeeye-job:v1.0.6
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: harbor-test
```
