### ISSUE TITLE
ke fails with error "no Auth Provider found for name azure"

### ISSUE THREAD

**Issue by masterphenix** [kubesphere/kubeeye#61]
Hello,
I have an AKS cluster in Azure, and I am authenticating  with Azure AD. My kubeconfig looks like this :
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxx
    server: https://myakscluster.hcp.westeurope.azmk8s.io:443
  name: myakscluster
contexts:
- context:
    cluster: myakscluster
    user: clusterUser_myakscluster-rg_myakscluster
  name: myakscluster
current-context: myakscluster
kind: Config
preferences: {}
users:
- name: clusterUser_myakscluster-rg_myakscluster
  user:
    auth-provider:
      config:
        apiserver-id: xxxxxxxxx
        client-id: xxxxxxxxxxxx
        config-mode: '1'
        environment: AzurePublicCloud
        tenant-id: xxxxxxxx
      name: azure
```
When I try to use kubeeye, I get the following error :
```
$ ke diag --kubeconfig ~/.kube/config
ERRO[0000] Error fetching api: no Auth Provider found for name "azure"
Failed to get cluster information: no Auth Provider found for name "azure"
```

Do you plan to support this provider in the future ?
